@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor forbruger
boundary customizedcarportorderpage.jsp
boundary receiptpage.jsp
control FrontController
participant Command
participant SubmitOrderCommand
participant OrderFacade
participant OrderMapper
participant OrderLineFacade
participant OrderLineMapper
participant Order
participant Calculator
database carport



forbruger -> customizedcarportorderpage.jsp: Start
customizedcarportorderpage.jsp -> FrontController: doPost()
FrontController -> FrontController: processRequest()
FrontController -> Command: fromPath()
Command --> FrontController: :SubmitOrderCommand
FrontController -> SubmitOrderCommand: execute()
SubmitOrderCommand -> OrderFacade: insertOrder()
OrderFacade -> OrderMapper: insertOrder()
OrderMapper -> carport: executeUpdate()
carport --> OrderMapper: ResultSet
OrderMapper -> OrderMapper: validate resultset
OrderMapper -> OrderMapper: insertCarport()
OrderMapper -> carport: executeUpdate()
carport --> OrderMapper: ResultSet
OrderMapper -> OrderMapper: validate Resultset
OrderMapper --> OrderFacade: Order
OrderFacade --> SubmitOrderCommand: Order
SubmitOrderCommand -> Calculator: calculateBOM()
Calculator -> Calculator: calculateSpær()
Calculator -> Calculator: calculateOptimalDistance()
Calculator -> Calculator: calculateStolper()
Calculator -> Calculator: getOptimalMaterial()
Calculator -> Calculator: getOptimalRoofUnits()
Calculator -> Calculator: calculateRoofSideMaterial()
Calculator -> Calculator: getMaterialByMaterialVariantId()
Calculator --> SubmitOrderCommand: BOM
SubmitOrderCommand -> OrderLineFacade: insertOrderLine()
OrderLineFacade -> OrderLineMapper: insertOrderLine()
OrderLineMapper -> carport: executeUpdate()
carport --> OrderLineMapper: OK
OrderLineMapper --> OrderLineFacade: OK
OrderLineFacade --> SubmitOrderCommand: OK
SubmitOrderCommand -> Order: calculateCostPriceByArrayList()
Order --> SubmitOrderCommand: OK
SubmitOrderCommand -> Order: calculateTotalPrice()
Order --> SubmitOrderCommand: OK
SubmitOrderCommand -> OrderFacade: updateOrderTotalPrice()
OrderFacade -> OrderMapper: updateOrderTotalPrice()
OrderMapper -> carport: executeUpdate()
carport --> OrderMapper: OK
OrderMapper --> OrderFacade: OK
OrderFacade --> SubmitOrderCommand: OK
SubmitOrderCommand --> FrontController: receiptpage
FrontController --> receiptpage.jsp: forward()



@enduml